name: Build

on:
  push:
    tags: [ v* ]

permissions:
  contents: write

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o build/aws-ecr-get-login-password-linux-amd64 -v main.go
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o build/aws-ecr-get-login-password-linux-arm64 -v main.go
          GOOS=darwin GOARCH=amd64 go build -o build/aws-ecr-get-login-password-darwin-amd64 -v main.go
          GOOS=darwin GOARCH=arm64 go build -o build/aws-ecr-get-login-password-darwin-arm64 -v main.go

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            build/aws-ecr-get-login-password-linux-amd64
            build/aws-ecr-get-login-password-linux-arm64
            build/aws-ecr-get-login-password-darwin-amd64
            build/aws-ecr-get-login-password-darwin-arm64
