name: "Go Dependency Submission"

on:
  push:
    branches: [ main ]

permissions:
  contents: write


jobs:
  go-action-detection:
    name: Submit dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Run snapshot action
        uses: actions/go-dependency-submission@v1
        with:
          go-mod-path: go.mod
          go-build-target: main.go
